### ISSUE TITLE
Completed module 3 assignments

### ISSUE THREAD

**Issue by b3nharris** [ds4owd-001/md-03-assignments-b3nharris#1]
Hi @larnsce @mianzg @sskorik01 

Completed part 1 of the assignments. There are a few comments in the code which are questions to myself - either to find out or maybe ask at office hours.

Sorry I missed the course last week - was moving possessions from the UK to France, but have caught up and looking forward to tomorrow.

**Comment by sskorik01** [comment]
Well done! I tried to answer your questions below:

1) Starting with `penguins`, group the data by species and year, then create a summary table containing the mean bill depth (call this bill_depth_mean), the mean bill length (call this bill_length_mean), and the count for each group. How will you handle NA values?

```{r}
penguins |> 
  filter(!is.na(bill_depth_mm), !is.na(bill_length_mm)) |> 
  group_by(species, year) |> 
  summarise(bill_depth_mean = mean(bill_depth_mm),
            bill_length_mean = mean(bill_length_mm),
            count= n())

#why can't mean handle NA values the same as max/min?
```
The behavior of different statistical functions, like mean, max, and min, with missing values (NA) in data can vary due to how they handle such cases.

max and min functions, by default, often have a mechanism to exclude NA values when computing the maximum or minimum value within a dataset. This exclusion is performed implicitly. When calculating the maximum or minimum of a set of numbers, any NA values are simply ignored, and the calculation proceeds based on the available data points.

On the other hand, the mean function typically requires a bit more nuance in handling missing values. By default, if there are any NA values present in the dataset, mean will return NA to indicate that the result is undefined or indeterminate due to the presence of missing values. This behavior helps to signify that the mean cannot be accurately calculated because the dataset is incomplete.


2) Use the `count()` function to count the number of observations for each species in `penguins`.

```{r}
penguins |> 
  group_by(species) |> 
  summarise(count = n())

#don't need to group/summarise - just use count
```
Yes, count() will automatically group the same species together and count how many times they occur.

**Comment by b3nharris** [comment]
Thanks for answering the questions Sophia - the explanation on handling NA values was really helpful.

Ben
